#!/sbin/openrc-run
# Copyright 2019 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

name="qubes early settings for vm"
description="Qubes VM early settings"
depend() {
    need localmount qubes-db
    before hostname
}

start() {
    . /usr/lib/qubes/init/functions

    if ! is_protected_file /etc/hostname ; then
        local name=$(qubesdb-read /name)
        if [ -n "$name" ]; then
            einfo "setting hostname to ${name}"
            echo "$name" > /etc/hostname
            sed -i "s/^\(127\.0\.0\.1\(\s.*\)*\s\).*$/\1${name}/" /etc/hosts
            sed -i "s/^\(::1\(\s.*\)*\s\).*$/\1${name}/" /etc/hosts
        fi
    fi

    if ! is_protected_file /etc/timezone ; then
        local timezone=$(qubesdb-read /qubes-timezone 2> /dev/null)
        if [ -n "$timezone" ]; then
            einfo "setting timezone to ${timezone}"
            ln -sf /usr/share/zoneinfo/"${timezone}" /etc/localtime
            echo "$timezone" > /etc/timezone
        fi
    fi
}
