#!/sbin/openrc-run
# Copyright 2019 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

name="qubes-networking"
description="set up qubes networking"

depend() {
	need qubes-db
	provide net
}

qread() {
	echo "$(qubesdb-read /qubes-${1})" 2>/dev/null
}

_apply() {
	local ip gw ns1 ns2

	ip=$(qread ip)
	gw=$(qread gateway)
	if [ -z $ip ] || [ -z $gw ]; then exit 1; fi
	ns1=$(qread primary-dns)
	ns2=$(qread secondary-dns)

	if [ "$1" = start ]; then
		ip link set up eth0 || exit 2
		ip addr add "$ip" dev eth0 || exit 2
		ip route add "$gw" dev eth0 || exit 2
		ip route add default via "$gw" || exit 2
		echo "namserver $ns1" > /etc/resolv.conf
		echo "namserver $ns2" >> /etc/resolv.conf
	elif [ "$1" = stop ]; then
		ip addr del "$ip"/32 dev eth0 || exit 2
		ip route del default || exit 2
		ip route del "$gw" dev eth0 || exit 2
		ip link set down eth0 || exit 2
		sed -i "/$ns1/d;/$ns2/d;" /etc/resolv.conf
	fi
}

start() {
	ebegin "Starting $name"
	_apply start
	eend $?
}

stop() {
	ebegin "Stopping $name"
	_apply stop
	eend $?
}
