#!/sbin/runscript
# Copyright 1999-2011 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Header: $

depend() {
	before xdm
}

start() {
	ebegin "Hiding plymouth splash"
	if pgrep plymouthd >/dev/null; then
		/bin/plymouth --quit
		chvt 7
        fi
	eend $?
}

stop() {
	ebegin "Showing plymouth splash"
	/sbin/plymouthd && /bin/plymouth --show-splash
	eend $?
}
